"""项目配置"""

from pathlib import Path


ROOT_DIR = Path(__file__).parent
MODEL_DIR = ROOT_DIR / ".cache" / "DialoGPT-small"
DATA_DIR = ROOT_DIR / "data"
CHECKPOINT_DIR = ROOT_DIR / "checkpoints"

EOS_ID = 50256
VOCAB_SIZE = 50257
CONTEXT_LENGTH = 256

N_POSITIONS = 1024
N_LAYER = 12
N_HEAD = 12
N_EMBD = 768
DROPOUT = 0.1
LAYER_NORM_EPSILON = 1e-5

BATCH_SIZE = 2
ACCUMULATION_STEPS = 16
MAX_STEPS = 2500
LEARNING_RATE = 2e-5
MIN_LEARNING_RATE = 2e-6
WARMUP_STEPS = 100
WEIGHT_DECAY = 0.01
GRAD_CLIP = 1.0
SEED = 1337
VALIDATION_INTERVAL = 50
VALIDATION_BATCHES = 20

MAX_NEW_TOKENS = 50
TEMPERATURE = 0.75
TOP_K = 50
REPETITION_PENALTY = 1.1

WANDB_PROJECT = "min-GPT"
